#!/bin/bash
# SPDX-License-Identifier: GPL-3.0

work_dir=$(pwd)
source $work_dir/functions.sh
ANDROID_VER=$(cat $work_dir/bin/ddevice/androidver.txt)
DEVICE_MODEL=$(cat $work_dir/bin/ddevice/device_model.txt)
BASE_BUILD_ID=$(cat $work_dir/bin/ddevice/base_build_id.txt)
BRAND=$(cat $work_dir/bin/ddevice/brand.txt)

# Determine Version and Status
if [[ $(git branch --show-current) == "beta" ]]; then
    VERSION="$(cat $work_dir/Version)"
    status="Beta"
else
    VERSION="$(cat $work_dir/Version)"
    status="Official"
fi

# Determine Brand Name
if [[ $BRAND == "OnePlus" ]]; then
  NTBUILD="ColorOS"
elif [[ $BRAND == "OnePlus_Global" ]]; then
  NTBUILD="OxygenOS"
elif [[ $BRAND == "RealmeUI" ]]; then
  NTBUILD="RealmeUI"
fi

echo "[SCRIPT] - Preparing files for upload..."

# 1. Grab the exact filename generated by packROM-Fastboot.sh
ORIGINAL_ZIP="out/${NTBUILD}_${DEVICE_MODEL}_${ANDROID_VER}_OS${BASE_BUILD_ID}_Fastboot.zip"

# 2. Calculate hash and rename
hash=$(md5sum "$ORIGINAL_ZIP" | head -c 5)
FINAL_ZIP_NAME="${NTBUILD}_${VERSION}_${DEVICE_MODEL}_OS${BASE_BUILD_ID}_${hash}_${status}_Fastboot.zip"
FINAL_ZIP_PATH="out/${FINAL_ZIP_NAME}"

mv "$ORIGINAL_ZIP" "$FINAL_ZIP_PATH"
echo "[SCRIPT] - Output: $FINAL_ZIP_PATH"

# 3. Split the file to avoid GitHub's 2GB Release limit
echo "[GITHUB] - Splitting ROM into 1.9GB parts..."
split -b 1900M "$FINAL_ZIP_PATH" "${FINAL_ZIP_PATH}.part"

echo "[GITHUB] - Uploading to GitHub Releases..."

# GITHUB_REPOSITORY is automatically provided by the GitHub Actions runner (e.g., username/repo)
GITHUB_REPO="${GITHUB_REPOSITORY}"

RELEASE_TAG="${DEVICE_MODEL}-${VERSION}-${status}-Fastboot"
RELEASE_TITLE="${NTBUILD} for ${DEVICE_MODEL} - v${VERSION} (${status}) [Fastboot]"

# 4. Create the release and upload ALL split parts
gh release create "$RELEASE_TAG" "${FINAL_ZIP_PATH}.part"* \
  --repo "$GITHUB_REPO" \
  --title "$RELEASE_TITLE" \
  --notes "Automated Fastboot ROM build for ${DEVICE_MODEL}.<br>Build ID: ${BASE_BUILD_ID}<br>MD5: ${hash}<br><br>**⚠️ IMPORTANT:** This ROM is split into multiple parts. You MUST combine them before extracting and flashing."

if [ $? -eq 0 ]; then
  echo "[GITHUB] - Upload successful!"
else
  echo "[GITHUB] - Error uploading file to GitHub Releases."
  exit 1
fi

# 5. Clean up the workspace
echo "[SYSTEM] - Clean Workflow.."
rm -rf "$work_dir/out"
rm -rf "$work_dir/build"

echo "[INFO] - Build ${NTBUILD}_${VERSION} for ${DEVICE_MODEL} successful!"
